# After changing this file, run it through http://lint.travis-ci.org/
# Generates 4 builds, the ones for python3 will install external wheels
language: python
python:
  - 2.6
  - 2.7
matrix:
  include:
    - python: 3.2
      env:
        - NUMPYSPEC===1.7.1
    - python: 3.3
      env:
        - NUMPYSPEC===1.8.0
before_install:
  - sudo add-apt-repository -y ppa:biometrics/bob
  - sudo add-apt-repository -y ppa:biometrics/bob.preview
  - sudo apt-get update -qq
  - sudo apt-get install -qq --force-yes bob-dev
  - if [ -n "${NUMPYSPEC}" ]; then sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran; fi
  - if [ -n "${NUMPYSPEC}" ]; then pip install --upgrade pip setuptools; fi
  - if [ -n "${NUMPYSPEC}" ]; then pip install --find-links http://wheels.astropy.org/ --find-links http://wheels2.astropy.org/ --use-wheel numpy$NUMPYSPEC sphinx nose; fi
  - pip install coveralls
install:
  - "python bootstrap.py"
  - "./bin/buildout"
script:
  - "./bin/python -c 'from xbob.learn.activation import get_config; print(get_config())'"
  - "./bin/coverage run --source=xbob.learn.activation ./bin/nosetests -sv"
  - "./bin/sphinx-build -b doctest doc sphinx"
  - "./bin/sphinx-build -b html doc sphinx"
after_success:
  - "coveralls"
